# ... (giữ nguyên các cài đặt khác) ...

# Cập nhật menu điều hướng
navigation:
  - name: Dịch vụ
    link: /agency/
  - name: Case Studies
    link: /case-studies/
  - name: Insights (Blog)
    link: /blog/
  - name: Về chúng tôi
    link: /about/

# ... (giữ nguyên các cài đặt khác) ...
