# ... (Nội dung file _config.yml của anh) ...

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .github/
  - admin/
  - countdownlastdaysisterquyen/
  - ngaynghidepnhat/
  - tarot/index.html
  - tarot/indexbackup.html
  
  # === THÊM DÒNG NÀY ĐỂ TRÁNH LỖI SCSS ===
  - assets/css/style.scss
