backend:
  name: github
  repo: pixelaquarius/Website-MIAS   # repo chá»©a website
  branch: main
  base_url: https://decap-cms-oauth-rouge.vercel.app
  auth_endpoint: /api/auth

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
